### ISSUE TITLE
创建项目状态不可选

### ISSUE THREAD

**Issue by banks-zhang** [cgpipline/strack#113]
必填信息
名称
strack
状态 （状体下拉菜单为空 自行填写 无法进行下一步。 ）
strack
公开
公开

**Comment by weijer** [comment]
用的 docker-compose 装的？

**Comment by banks-zhang** [comment]
一键部署脚本。我等会儿 QQ截图给你瞅瞅。

**Comment by banks-zhang** [comment]
重新安装 过可以了。 我再试试看这个问题怎么出现的

**Comment by weijer** [comment]
好的
